(() => {
  const $ = id => document.getElementById(id), text = $('research-text'), humanInput = $('humanize-input'), notice = $('notice');
  const levels = {1:'تصحيح لغوي خفيف: علامات الترقيم والأخطاء الواضحة.',2:'تحسين محدود: وضوح أفضل وانتقالات أنعم.',3:'إعادة تنظيم معتدلة: ترابط وصياغة أكاديمية.',4:'إعادة صياغة واسعة: بنية وأساليب أكثر نضجًا.',5:'تحرير عميق: تغيير أكبر في الأسلوب مع ثبات الحقائق والمراجع.'};
  let selectedLevel = 3;
  const showNotice = (message, error = false) => { notice.textContent = message; notice.className = `notice ${error ? 'error' : ''}`; };
  const words = value => value.trim() ? value.trim().split(/\s+/).filter(Boolean) : [];
  const setText = value => { text.value = value; $('word-count').textContent = `${words(value).length} كلمة`; };
  const extension = name => name.toLowerCase().split('.').pop();
  const readPdf = async file => { if (!window.pdfjsLib) throw new Error('تعذر تحميل محرك PDF. تحقق من الاتصال ثم حاول مرة أخرى.'); window.pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const pdf = await window.pdfjsLib.getDocument({data: await file.arrayBuffer()}).promise; const pages=[]; for(let n=1;n<=pdf.numPages;n+=1){const page=await pdf.getPage(n);const content=await page.getTextContent();pages.push(content.items.map(item=>item.str||'').join(' '));} return pages.join('\n\n').trim(); };
  const readDocx = async file => { if (!window.mammoth) throw new Error('تعذر تحميل محرك DOCX. تحقق من الاتصال ثم حاول مرة أخرى.'); return (await window.mammoth.extractRawText({arrayBuffer: await file.arrayBuffer()})).value.trim(); };
  const variance = values => { if (!values.length) return 0; const mean=values.reduce((a,b)=>a+b,0)/values.length; return Math.sqrt(values.reduce((sum,n)=>sum+(n-mean)**2,0)/values.length); };
  const analyzeSentences = value => {
    const sentences = value.split(/(?<=[.!؟؛])\s+|\n+/).map(sentence=>sentence.trim()).filter(sentence=>words(sentence).length >= 5);
    const lengths = sentences.map(sentence=>words(sentence).length); const average = lengths.length ? lengths.reduce((a,b)=>a+b,0)/lengths.length : 0; const spread = variance(lengths); const transitions = /(إضافة إلى ذلك|من ناحية أخرى|في هذا السياق|بناءً على ما سبق|تجدر الإشارة|علاوة على ذلك|بشكل عام|من جهة أخرى)/g;
    return sentences.map((sentence,index) => { const tokens=words(sentence); const unique=new Set(tokens.map(token=>token.toLowerCase())).size; let score=28; const reasons=[]; if(average>0 && spread/average<.24 && sentences.length>=3){score+=16;reasons.push('إيقاع منتظم');} if(tokens.length>=14 && tokens.length<=30){score+=8;reasons.push('طول نمطي');} if(unique/Math.max(tokens.length,1)<.7){score+=10;reasons.push('تنوع مفردات منخفض');} if(transitions.test(sentence)){score+=8;reasons.push('انتقال نمطي');} transitions.lastIndex=0; if((sentence.match(/[،,:]/g)||[]).length>=3){score+=4;reasons.push('تركيب مصقول');} score=Math.max(5,Math.min(94,score)); return {sentence,index,score,reasons:reasons.length?reasons:['لا توجد إشارة قوية']}; });
  };
  const renderSentenceResults = analyzed => { const host=$('sentence-results'); if(!host)return; if(!analyzed.length){host.innerHTML='';return;} const top=[...analyzed].sort((a,b)=>b.score-a.score).slice(0,5); host.innerHTML=`<div class="sentence-results-title"><span>خريطة الجمل</span><small>${analyzed.length} جملة محللة</small></div>${top.map(item=>`<div class="sentence-result ${item.score>=60?'high':item.score>=40?'medium':'low'}"><span>${item.score}%</span><p>${item.sentence}</p><small>${item.reasons.join(' · ')}</small></div>`).join('')}`; };
  $('word-count').textContent='0 كلمة'; text.addEventListener('input',()=>{$('word-count').textContent=`${words(text.value).length} كلمة`;}); $('clear-text').addEventListener('click',()=>setText(''));
  document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item===tab));const upload=tab.dataset.tab==='upload';$('paste-box').classList.toggle('hidden',upload);$('upload-box').classList.toggle('hidden',!upload);}));
  $('upload-box').addEventListener('click',event=>{if(event.target!==$('file-input'))$('file-input').click();});
  $('file-input').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;$('file-name').textContent=`${file.name} · جاري استخراج النص…`;showNotice('جاري استخراج النص من الملف، يرجى الانتظار…');try{const ext=extension(file.name);let extracted='';if(['txt','md','html','htm'].includes(ext))extracted=await file.text();else if(ext==='pdf')extracted=await readPdf(file);else if(ext==='docx')extracted=await readDocx(file);else throw new Error('نوع الملف غير مدعوم. استخدم PDF أو DOCX أو TXT.');if(extracted.length<40)throw new Error('لم يتم العثور على نص قابل للاستخراج. قد يكون PDF صورة ممسوحة ضوئيًا.');setText(extracted);document.querySelector('[data-tab="paste"]').click();$('file-name').textContent=`${file.name} · تم استخراج النص بنجاح`;showNotice(`تم استخراج ${words(extracted).length} كلمة من الملف بنجاح.`);}catch(error){$('file-name').textContent=file.name;showNotice(error instanceof Error?error.message:'تعذر استخراج النص من الملف.',true);}});
  const renderIntegrityFlags = value => { const host=$('integrity-flags'); if(!host)return; const zeroWidth=/[\u200B-\u200D\uFEFF]/.test(value); const mixedScript=/[A-Za-z]/.test(value)&&/[\u0400-\u04FF]/.test(value); const images=/\[image\]|\!\[[^\]]*\]\([^)]*\)/i.test(value); const flags=[['الرموز الخفية',zeroWidth?'تم العثور على رموز غير مرئية':'لم تُرصد',zeroWidth],['اختلاط الأبجديات',mixedScript?'تحتاج مراجعة يدوية':'لم يُرصد',mixedScript],['محتوى صور',images?'وجدت إحالات صور داخل النص':'لم تُرصد',images]]; host.innerHTML=`<div class="integrity-title"><span>فحوص النزاهة التقنية</span><small>مؤشرات مساعدة</small></div>${flags.map(flag=>`<div class="integrity-row ${flag[2]?'warning':''}"><span>${flag[2]?'!':'✓'}</span><b>${flag[0]}</b><small>${flag[1]}</small></div>`).join('')}`; };
  $('scan-btn').addEventListener('click',()=>{const content=text.value.trim();if(content.length<120)return showNotice('لنتيجة أكثر موثوقية أدخل 120 حرفًا على الأقل، ويفضل 300 كلمة أو أكثر.',true);const analyzed=analyzeSentences(content);const sentenceScores=analyzed.map(item=>item.score);const ai=sentenceScores.length?Math.round(sentenceScores.reduce((a,b)=>a+b,0)/sentenceScores.length):30;const tokens=words(content).map(token=>token.toLowerCase());const ngrams=[];for(let i=0;i<tokens.length-3;i+=1)ngrams.push(tokens.slice(i,i+4).join(' '));const counts=ngrams.reduce((map,gram)=>(map[gram]=(map[gram]||0)+1,map),{});const repeatedNgrams=Object.values(counts).filter(count=>count>1).reduce((sum,count)=>sum+count-1,0);const similarity=Math.min(98,Math.max(0,Math.round((repeatedNgrams/Math.max(tokens.length-3,1))*100)));$('ai-score').innerHTML=`${ai}<em>%</em>`;$('similarity-score').innerHTML=`${similarity}<em>%</em>`;$('ai-bar').style.width=`${ai}%`;$('similarity-bar').style.width=`${similarity}%`;$('scan-status').textContent='اكتمل التحليل الجُملي';renderSentenceResults(analyzed);renderIntegrityFlags(content);const similarityBand=similarity<25?'تشابه منخفض':similarity<50?'تشابه متوسط':'تشابه مرتفع';showNotice(`اكتمل التحليل. ${similarityBand}. نسبة AI مؤشر احتمالي وليست إثباتًا لمصدر النص.`);});
  document.querySelectorAll('[data-level]').forEach(button=>button.addEventListener('click',()=>{selectedLevel=Number(button.dataset.level);document.querySelectorAll('[data-level]').forEach(item=>item.classList.toggle('selected',item===button));$('level-value').textContent=selectedLevel;$('level-description').textContent=levels[selectedLevel];}));
  $('humanize-btn').addEventListener('click',()=>{const value=humanInput.value.trim();if(value.length<40)return showNotice('أدخل 40 حرفًا على الأقل لتحسين النص.',true);let output=value.replace(/\s+/g,' ').trim();if(selectedLevel>=2)output=output.replace(/،/g,'، ').replace(/\s+/g,' ');if(selectedLevel>=3)output=output.replace(/\bمن خلال\b/g,'عبر').replace(/\bبهدف\b/g,'من أجل');if(selectedLevel>=4)output=output.replace(/\bوفي هذا السياق\b/g,'وفي هذا الإطار').replace(/\bيهدف البحث إلى\b/g,'يسعى هذا البحث إلى');if(selectedLevel>=5)output=output.replace(/\bبشكل كبير\b/g,'على نحو ملحوظ').replace(/\bكما أن\b/g,'إضافة إلى ذلك، فإن');$('result-text').textContent=output;$('humanize-result').classList.remove('hidden');showNotice('تم تحسين الصياغة محليًا. راجع النص وأفصح عن استخدام أدوات المساعدة حسب سياسة مؤسستك.');});
  $('copy-result').addEventListener('click',async()=>{await navigator.clipboard?.writeText($('result-text').textContent);$('copy-result').textContent='تم النسخ';setTimeout(()=>$('copy-result').textContent='نسخ النص',1500);});
})();
